version: '3.9'

services:

  tallymobile-backend:
    build:
      context: ./tally-backend
      dockerfile: Dockerfile
    container_name: tallymobile-backend
    restart: unless-stopped
    expose:
      - "4000"
    env_file:
      - ./tally-backend/.env
    networks:
      - prod-network

networks:
  prod-network:
    external: true
